#include <emscripten/bind.h>
#include "color.h"

using namespace emscripten;

EMSCRIPTEN_BINDINGS(color) {
	class_<CHSV>("CHSV")
		.constructor<uint8_t, uint8_t, uint8_t>()
		.property("hue", &CHSV::hue)
		.property("sat", &CHSV::sat)
		.property("val", &CHSV::val)
		;

	class_<CRGB>("CRGB")
		.constructor<uint8_t, uint8_t, uint8_t>()
		.class_function("fromColorCode", &CRGB::fromColorCode)
		.class_function("clone", &CRGB::clone)
		.class_function("fromHSV", &CRGB::fromHSV)
		.property("r", &CRGB::r)
		.property("g", &CRGB::g)
		.property("b", &CRGB::b)

		.function("setHSV", &CRGB::setHSV)
		.function("setHue", &CRGB::setHue)
		.function("setColorCode", &CRGB::setColorCode)

		.function("add", &CRGB::operator+=)
		.function("addToRGB", &CRGB::addToRGB)
		.function("inc", select_overload<CRGB &()>(&CRGB::operator++))

		.function("subtract", &CRGB::operator-=)
		.function("subtractFromRGB", &CRGB::subtractFromRGB)
		.function("dec", select_overload<CRGB &()>(&CRGB::operator--))

		.function("mul", &CRGB::operator*=)
		.function("div", &CRGB::operator/=)
		.function("rsh", &CRGB::operator>>=)

		.function("nscale8_video", &CRGB::nscale8_video)
		.function("fadeLightBy", &CRGB::fadeLightBy)
		.function("nscale8", select_overload<CRGB&(uint8_t)>(&CRGB::nscale8))
		.function("nscale8_channels", select_overload<CRGB&(const CRGB&)>(&CRGB::nscale8))
		.function("fadeToBlackBy", &CRGB::fadeToBlackBy)

		.function("or", select_overload<CRGB&(uint8_t)>(&CRGB::operator |=))
		.function("or_channels", select_overload<CRGB&(const CRGB&)>(&CRGB::operator |=))
		.function("and", select_overload<CRGB&(uint8_t)>(&CRGB::operator &=))
		.function("and_channels", select_overload<CRGB&(const CRGB&)>(&CRGB::operator &=))

		.function("invert", &CRGB::operator-)

		.function("lerp8", &CRGB::lerp8)
		.function("lerp16", &CRGB::lerp16);

	enum_<CRGB::HTMLColorCode>("HTMLColorCode")
		.value("AliceBlue", CRGB::AliceBlue)
		.value("Amethyst", CRGB::Amethyst)
		.value("AntiqueWhite", CRGB::AntiqueWhite)
		.value("Aqua", CRGB::Aqua)
		.value("Aquamarine", CRGB::Aquamarine)
		.value("Azure", CRGB::Azure)
		.value("Beige", CRGB::Beige)
		.value("Bisque", CRGB::Bisque)
		.value("Black", CRGB::Black)
		.value("BlanchedAlmond", CRGB::BlanchedAlmond)
		.value("Blue", CRGB::Blue)
		.value("BlueViolet", CRGB::BlueViolet)
		.value("Brown", CRGB::Brown)
		.value("BurlyWood", CRGB::BurlyWood)
		.value("CadetBlue", CRGB::CadetBlue)
		.value("Chartreuse", CRGB::Chartreuse)
		.value("Chocolate", CRGB::Chocolate)
		.value("Coral", CRGB::Coral)
		.value("CornflowerBlue", CRGB::CornflowerBlue)
		.value("Cornsilk", CRGB::Cornsilk)
		.value("Crimson", CRGB::Crimson)
		.value("Cyan", CRGB::Cyan)
		.value("DarkBlue", CRGB::DarkBlue)
		.value("DarkCyan", CRGB::DarkCyan)
		.value("DarkGoldenrod", CRGB::DarkGoldenrod)
		.value("DarkGray", CRGB::DarkGray)
		.value("DarkGrey", CRGB::DarkGrey)
		.value("DarkGreen", CRGB::DarkGreen)
		.value("DarkKhaki", CRGB::DarkKhaki)
		.value("DarkMagenta", CRGB::DarkMagenta)
		.value("DarkOliveGreen", CRGB::DarkOliveGreen)
		.value("DarkOrange", CRGB::DarkOrange)
		.value("DarkOrchid", CRGB::DarkOrchid)
		.value("DarkRed", CRGB::DarkRed)
		.value("DarkSalmon", CRGB::DarkSalmon)
		.value("DarkSeaGreen", CRGB::DarkSeaGreen)
		.value("DarkSlateBlue", CRGB::DarkSlateBlue)
		.value("DarkSlateGray", CRGB::DarkSlateGray)
		.value("DarkSlateGrey", CRGB::DarkSlateGrey)
		.value("DarkTurquoise", CRGB::DarkTurquoise)
		.value("DarkViolet", CRGB::DarkViolet)
		.value("DeepPink", CRGB::DeepPink)
		.value("DeepSkyBlue", CRGB::DeepSkyBlue)
		.value("DimGray", CRGB::DimGray)
		.value("DimGrey", CRGB::DimGrey)
		.value("DodgerBlue", CRGB::DodgerBlue)
		.value("FireBrick", CRGB::FireBrick)
		.value("FloralWhite", CRGB::FloralWhite)
		.value("ForestGreen", CRGB::ForestGreen)
		.value("Fuchsia", CRGB::Fuchsia)
		.value("Gainsboro", CRGB::Gainsboro)
		.value("GhostWhite", CRGB::GhostWhite)
		.value("Gold", CRGB::Gold)
		.value("Goldenrod", CRGB::Goldenrod)
		.value("Gray", CRGB::Gray)
		.value("Grey", CRGB::Grey)
		.value("Green", CRGB::Green)
		.value("GreenYellow", CRGB::GreenYellow)
		.value("Honeydew", CRGB::Honeydew)
		.value("HotPink", CRGB::HotPink)
		.value("IndianRed", CRGB::IndianRed)
		.value("Indigo", CRGB::Indigo)
		.value("Ivory", CRGB::Ivory)
		.value("Khaki", CRGB::Khaki)
		.value("Lavender", CRGB::Lavender)
		.value("LavenderBlush", CRGB::LavenderBlush)
		.value("LawnGreen", CRGB::LawnGreen)
		.value("LemonChiffon", CRGB::LemonChiffon)
		.value("LightBlue", CRGB::LightBlue)
		.value("LightCoral", CRGB::LightCoral)
		.value("LightCyan", CRGB::LightCyan)
		.value("LightGoldenrodYellow", CRGB::LightGoldenrodYellow)
		.value("LightGreen", CRGB::LightGreen)
		.value("LightGrey", CRGB::LightGrey)
		.value("LightPink", CRGB::LightPink)
		.value("LightSalmon", CRGB::LightSalmon)
		.value("LightSeaGreen", CRGB::LightSeaGreen)
		.value("LightSkyBlue", CRGB::LightSkyBlue)
		.value("LightSlateGray", CRGB::LightSlateGray)
		.value("LightSlateGrey", CRGB::LightSlateGrey)
		.value("LightSteelBlue", CRGB::LightSteelBlue)
		.value("LightYellow", CRGB::LightYellow)
		.value("Lime", CRGB::Lime)
		.value("LimeGreen", CRGB::LimeGreen)
		.value("Linen", CRGB::Linen)
		.value("Magenta", CRGB::Magenta)
		.value("Maroon", CRGB::Maroon)
		.value("MediumAquamarine", CRGB::MediumAquamarine)
		.value("MediumBlue", CRGB::MediumBlue)
		.value("MediumOrchid", CRGB::MediumOrchid)
		.value("MediumPurple", CRGB::MediumPurple)
		.value("MediumSeaGreen", CRGB::MediumSeaGreen)
		.value("MediumSlateBlue", CRGB::MediumSlateBlue)
		.value("MediumSpringGreen", CRGB::MediumSpringGreen)
		.value("MediumTurquoise", CRGB::MediumTurquoise)
		.value("MediumVioletRed", CRGB::MediumVioletRed)
		.value("MidnightBlue", CRGB::MidnightBlue)
		.value("MintCream", CRGB::MintCream)
		.value("MistyRose", CRGB::MistyRose)
		.value("Moccasin", CRGB::Moccasin)
		.value("NavajoWhite", CRGB::NavajoWhite)
		.value("Navy", CRGB::Navy)
		.value("OldLace", CRGB::OldLace)
		.value("Olive", CRGB::Olive)
		.value("OliveDrab", CRGB::OliveDrab)
		.value("Orange", CRGB::Orange)
		.value("OrangeRed", CRGB::OrangeRed)
		.value("Orchid", CRGB::Orchid)
		.value("PaleGoldenrod", CRGB::PaleGoldenrod)
		.value("PaleGreen", CRGB::PaleGreen)
		.value("PaleTurquoise", CRGB::PaleTurquoise)
		.value("PaleVioletRed", CRGB::PaleVioletRed)
		.value("PapayaWhip", CRGB::PapayaWhip)
		.value("PeachPuff", CRGB::PeachPuff)
		.value("Peru", CRGB::Peru)
		.value("Pink", CRGB::Pink)
		.value("Plaid", CRGB::Plaid)
		.value("Plum", CRGB::Plum)
		.value("PowderBlue", CRGB::PowderBlue)
		.value("Purple", CRGB::Purple)
		.value("Red", CRGB::Red)
		.value("RosyBrown", CRGB::RosyBrown)
		.value("RoyalBlue", CRGB::RoyalBlue)
		.value("SaddleBrown", CRGB::SaddleBrown)
		.value("Salmon", CRGB::Salmon)
		.value("SandyBrown", CRGB::SandyBrown)
		.value("SeaGreen", CRGB::SeaGreen)
		.value("Seashell", CRGB::Seashell)
		.value("Sienna", CRGB::Sienna)
		.value("Silver", CRGB::Silver)
		.value("SkyBlue", CRGB::SkyBlue)
		.value("SlateBlue", CRGB::SlateBlue)
		.value("SlateGray", CRGB::SlateGray)
		.value("SlateGrey", CRGB::SlateGrey)
		.value("Snow", CRGB::Snow)
		.value("SpringGreen", CRGB::SpringGreen)
		.value("SteelBlue", CRGB::SteelBlue)
		.value("Tan", CRGB::Tan)
		.value("Teal", CRGB::Teal)
		.value("Thistle", CRGB::Thistle)
		.value("Tomato", CRGB::Tomato)
		.value("Turquoise", CRGB::Turquoise)
		.value("Violet", CRGB::Violet)
		.value("Wheat", CRGB::Wheat)
		.value("White", CRGB::White)
		.value("WhiteSmoke", CRGB::WhiteSmoke)
		.value("Yellow", CRGB::Yellow)
		.value("YellowGreen", CRGB::YellowGreen)
		.value("FairyLight", CRGB::FairyLight)
		.value("FairyLightNCC", CRGB::FairyLightNCC)
		;
}
